const channels = ["전체", "또간집", "성시경 먹을텐데", "백종원"] as const;
const regions = ["전체 지역", "서울", "경기", "부산", "제주"] as const;

export default function DesignShowcase() {
  return (
    <main className="mx-auto min-h-dvh w-full max-w-[var(--shell-max-width)] bg-[var(--surface-paper)] px-5 py-8 text-[var(--ink-primary)]">
      <header className="flex items-start justify-between"><div><p className="font-[var(--font-display)] text-4xl font-bold leading-none text-[var(--accent-red)]">픽픽</p><p className="mt-2 text-sm text-[var(--ink-secondary)]">영상 속 진짜 맛집</p></div><button aria-label="메뉴 열기" className="flex size-12 items-center justify-center rounded-[var(--radius-control)] hover:bg-[var(--surface-muted)] active:scale-[0.96]"><svg aria-hidden="true" className="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M4 7h16M4 12h16M4 17h16" strokeLinecap="round" /></svg></button></header>
      <section aria-labelledby="primitive-heading" className="mt-8 space-y-4"><h1 id="primitive-heading" className="font-[var(--font-display)] text-[28px] font-bold leading-tight [text-wrap:balance]">채널이 늘어나도 같은 화면</h1><div className="flex gap-2 overflow-x-auto pb-1" aria-label="채널 선택">{channels.map((channel, index) => <button key={channel} aria-pressed={index === 0} className={`min-h-11 shrink-0 rounded-[var(--radius-control)] border px-4 text-sm font-semibold transition-[background-color,color,transform] duration-150 active:scale-[0.96] ${index === 0 ? "border-[var(--accent-red)] bg-[var(--accent-red)] text-[var(--surface-card)]" : "border-[var(--line-default)] bg-[var(--surface-card)] text-[var(--ink-primary)] hover:bg-[var(--surface-muted)]"}`}>{channel}</button>)}</div><label className="flex min-h-[var(--control-height)] items-center gap-3 rounded-[var(--radius-control)] border border-[var(--line-default)] bg-[var(--surface-card)] px-4 text-[var(--ink-tertiary)]"><svg aria-hidden="true" className="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><circle cx="11" cy="11" r="6.5" /><path d="m16 16 4 4" strokeLinecap="round" /></svg><span className="text-sm">식당이나 동네를 검색하세요</span></label><div className="flex gap-2 overflow-x-auto pb-1" aria-label="지역 선택">{regions.map((region, index) => <button key={region} aria-pressed={index === 0} className={`min-h-11 shrink-0 rounded-[var(--radius-control)] border px-4 text-sm font-semibold transition-[background-color,color,transform] duration-150 active:scale-[0.96] ${index === 0 ? "border-[var(--accent-red)] bg-[var(--accent-red)] text-[var(--surface-card)]" : "border-[var(--line-default)] bg-[var(--surface-card)] text-[var(--ink-primary)] hover:bg-[var(--surface-muted)]"}`}>{region}</button>)}</div></section>
      <section aria-label="맛집 목록" className="mt-8 divide-y divide-[var(--line-default)] border-y border-[var(--line-default)]">{["대림국수", "할매곱창"].map((restaurant) => <article key={restaurant} className="flex min-h-40 items-center gap-4 py-5"><div aria-hidden="true" className="size-28 shrink-0 rounded-[var(--radius-card)] bg-[var(--surface-muted)] outline outline-1 outline-[rgb(39_37_34_/_10%)]" /><div className="min-w-0"><h2 className="font-[var(--font-display)] text-[22px] font-bold">{restaurant}</h2><p className="mt-1 text-sm text-[var(--ink-secondary)]">성수동 · 꼬치국수</p><p className="mt-2 text-sm leading-6 text-[var(--ink-secondary)] [text-wrap:pretty]">영상 속에서 발견한 동네의 오래된 맛집.</p><span className="mt-3 inline-flex min-h-8 items-center rounded-[var(--radius-control)] border border-[var(--line-default)] bg-[var(--surface-card)] px-2 text-xs font-semibold">또간집 EP.45</span></div></article>)}</section>
    </main>
  );
}
